apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: giropops-senhas
  name: giropops-senhas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giropops-senhas
  strategy: {}
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
      - image: lpampolha/linuxtips-giropops-senhas:6.0
        name: giropops-senhas
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 128Mi
            cpu: 0.3
          requests:
            memory: 64Mi
            cpu: 0.1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
