apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployments.redis.name }}
spec:
  selector:
    app: {{ .Values.deployments.redis.labels.app }}
  ports:
    - protocol: {{ .Values.deployments.redis.service.protocol }}
      port: {{ .Values.deployments.redis.service.port }}
      targetPort: {{ .Values.deployments.redis.service.targetPort }}
  type: {{ .Values.deployments.redis.type }}
