{{- range $component, $config := .Values.configmaps }}
  {{- range $cmap := $config.data }}
apiVersion: v1
data:
  APP_IMAGE: {{ $cmap.image }}
  APP_NAME: {{ $cmap.name }}
kind: ConfigMap
metadata:
  name: configmap-{{ $cmap.name }}
---
  {{- end }}
{{- end }}
