{{- range $component, $config := .Values.ingress }}
  {{- range $svc := $config.endpoint }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $component }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ $svc.route }}
spec:
  rules:
  - http:
      paths:
      - path: {{ $svc.route }}
        pathType: Prefix
        backend:
          service:
            name: {{ $component  }}-app
            port:
              number: {{ $svc.ports.port }}
---
  {{- end }}
{{- end }}
